---
name: Bug Report
about: Create a report to help us improve
title: '[BUG]'
labels: bug
assignees: ''

body:
  - type: markdown
    attributes:
      value: "## Describe the bug\nA clear and concise description of what the bug is."

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: "Select the severity of the bug."
      options:
        - Low
        - Medium
        - High
        - Critical

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: "Provide steps to reproduce the bug."
      placeholder: "1. Go to '...'\n2. Click on '...'\n3. Scroll down to '...'\n4. See error"
      render: markdown

  - type: checkboxes
    id: terms
    attributes:
      label: Terms and Conditions
      description: "Please accept the terms and conditions."
      options:
        - label: I have searched the existing issues to make sure this is not a duplicate.
          required: true

---
